sudo: false

language: node_js
node_js:
  - "4"
  - "6"
  - "stable"

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache

before_install:
  # if npm version is less than 3.0.0, upgrade to 3
  - if [[ $(npm -v | cut -d '.' -f 1) -lt 3 ]]; then npm i -g npm@^3; fi
  - npm install -g bower phantomjs-prebuilt

install:
  - npm install
  - bower install

deploy:
  provider: npm
  email: stefan.penner+ember-cli@gmail.com
  api_key:
    secure: GJexXCwAwkiezqiivJLdCDcwHyNOkyWGhaIC9wEovlrmn6UZlNL1lZvkTHBMaxFRtTa5ZmwLWHCLPiNIbpqFb1JdSpmAq+7P/qjSMMm6JO8hlA8Yn57TP4rZKG++xKRjZe7f13K5yqrJWFtWyHiBppU047GAP8gBsBlcjUVzAGM=
  on:
    tags: true
    repo: ember-cli/ember-cli-eslint
