sudo: false

language: node_js
node_js:
  - "4"
  - "6"
  - "stable"

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add phantomjs-prebuilt
  - phantomjs --version

install:
  - yarn install --no-lockfile

deploy:
  provider: npm
  email: stefan.penner+ember-cli@gmail.com
  api_key:
    secure: GJexXCwAwkiezqiivJLdCDcwHyNOkyWGhaIC9wEovlrmn6UZlNL1lZvkTHBMaxFRtTa5ZmwLWHCLPiNIbpqFb1JdSpmAq+7P/qjSMMm6JO8hlA8Yn57TP4rZKG++xKRjZe7f13K5yqrJWFtWyHiBppU047GAP8gBsBlcjUVzAGM=
  on:
    tags: true
    repo: ember-cli/ember-cli-eslint
